### ISSUE TITLE
全体管理

### ISSUE THREAD

**Issue by K-Yuki1019** [camp-team/team-kumamoto2#1]
## MTG(修正中)
- [ ] issue確認MTG (2020.12.3 21:00 start)

### 事前準備
- [x] 要件定義・設計 @K-Yuki1019 
- [ ] issueを立てる @K-Yuki1019 
- [x] XDプロトタイプ作成  @K-Yuki1019 
- [x] サービス名考案 @yuuki-kouno 

## 環境構築
- [x]  Angular: 11.0.3
- [x]  Angular CLI: 11.0.3 @K-Yuki1019 
- [ ]  AngularMaterial @K-Yuki1019 
- [ ]  AngularFire  @K-Yuki1019 
- [ ]  自動Prettier  @K-Yuki1019 
- [ ]  自動deploy @K-Yuki1019 

### 共通画面
- [ ] Header作成　@mihye1128 #2 
- [ ] Footer作成     @Robinson-R1127  #3 

### Home画面(LP)　@Robinson-R1127  (メイン)　@K-Yuki1019 (サポート)
- [ ] Heroコンポーネント #5 
- [ ] Aboutコンポーネント #6 
- [ ] CatchCopyコンポーネント #7 

### My page画面
- [ ] My page @peyo-code #9
- [ ] History-list(カードまとめる画面) @peyo-code  #10
- [ ] History-Card @peyo-code #11
- [ ] Delete ~User-Dialog(My page画面でのみ)  @yuuki-kouno #12

### Setting画面(言葉登録画面) @K-Yuki1019 
- [ ] setting #14
- [ ] Message-List(HTMLで最新のHistoryにhistoryIDを持たせて、最新のプルリクが一番に表示されるように) #15
- [ ] Message-card #16
- [ ] Create-Message-Dialog #17
- [ ] Delete-Message-Dialog #17

### 404ページ
- [ ] Not-Found @yuuki-kouno #18

## 機能実装
- [ ] ログイン/ ログアウト(初ログインした際に辞書に適当なのを一つ作る) @mihye1128 #19
- [ ] messageのCRUD+Getメソッド (主要機能なのですぐ作る) @K-Yuki1019 #21
- [ ] interface作成 @K-Yuki1019 #20 
- [ ] Guard(CanLoad/  CanActivate @Robinson-R1127 #22
- [ ] HistoryService(getHistory→History一覧を持ってくる) @peyo-code #23

Functions(Githubにプッシュした時)
- [ ] createHistory  @mihye1128 #24
- [ ] deleteHistory(バッチ処理) @yuuki-kouno #25

## MindNode
![image](https://user-images.githubusercontent.com/63516648/100959784-60adc480-3562-11eb-8079-675b921cf0b5.png)

## XD
![image](https://user-images.githubusercontent.com/63516648/100953499-0f97d380-3556-11eb-87bd-0c0ee067c22e.png)
