### ISSUE TITLE
(My page) 全体管理

### ISSUE THREAD

**Issue by K-Yuki1019** [camp-team/team-kumamoto2#8]
## 実装イメージ
![image](https://user-images.githubusercontent.com/63516648/100960374-77a0e680-3563-11eb-8058-1d5e4cd9fa4f.png)

- [ ] My page @peyo-code #9 

- [ ] History-list @peyo-code #10 

- [ ] History-card @peyo-code #11 

- [ ] Delete-user-dialog @yuuki-kouno #12
